---
title: "Visualization EDA"
author: "Nathan Miller"
date: "11/30/2021"
output: html_document
---

# Setup and Load
```{r, warning=F, message=F}
library(sf)
library(ggmap)
library(leaflet)
library(dplyr)

census <- st_read("Data/2010_CensusData/2010_CensusData.shp") 
city_council_dist <- st_read("Data/City_Council_Districts/City_Council_Districts.shp")
school_boundaries <- st_read("Data/School_Boundaries/School_Boundaries.shp")

business_licenses_df <- read.csv("Data/Business_Licenses_geocoded.csv")%>% 
  st_as_sf(coords = c("X","Y"), 
           crs = "+proj=longlat +datum=WGS84 +ellps=WGS84")

parks_df <- read.csv("Data/Parks_Locations_and_Features.csv") %>% 
  st_as_sf(coords = c("Lon","Lat"), 
           crs = "+proj=longlat +datum=WGS84 +ellps=WGS84")

public_facilities_df <- read.csv("Data/Public_Facilities.csv") %>% 
  st_as_sf(coords = c("Lon","Lat"), 
           crs = "+proj=longlat +datum=WGS84 +ellps=WGS84")

```

```{r}
### Add Var names to relevant Census columns 
census <- census %>% 
  dplyr::rename(Population = SE_T001_00,
                age_u5 = SE_T008_02,
                age_5_9 = SE_T008_03,
                age_11_14 = SE_T008_04,
                age_15_17 = SE_T008_05,
                age_18_24 = SE_T008_06,
                age_25_34 = SE_T008_07,
                age_35_44 = SE_T008_08,
                age_45_54 = SE_T008_09,
                age_55_64 = SE_T008_10,
                age_65_74 = SE_T008_11,
                age_75_84 = SE_T008_12,
                ## There should be an Over 85 column but not in the provided data... maybe total pop - sum(all existing ages)?
                occupied_houses = SE_T069_01, 
                owner_occupied = SE_T069_02) %>% 
  dplyr::mutate(renter_occupied = occupied_houses - owner_occupied, 
                age_o85 = Population - (age_u5+ age_5_9+ age_11_14+ age_15_17+ age_18_24+ age_25_34+ age_35_44+ age_45_54+ age_55_64+ age_65_74+ age_75_84))

```

# Census data to disctricts
```{r}
# Convert Census CRS to WGS84
census_transformed <- census %>% 
  select(geometry, GEOID, Population, contains('age'), contains('occupied')) %>% # Add relevant census metrics... 
  st_transform(crs = st_crs(city_council_dist)) %>% 
  mutate(c_area = units::drop_units(st_area(.))) #what are the units for area?
  
sf::sf_use_s2(FALSE) # reformat CRS to fix?? 
# Set Buffer = 0 to fix city council topology
city_council_dist2 <- sf::st_buffer(city_council_dist, dist = 0)
sf::sf_use_s2(TRUE)


# Create a polygon for every district 
all_councils <- city_council_dist2 %>% 
  mutate(agg = 'All') %>% 
  group_by(agg) %>% 
  summarise() %>% 
  mutate(OBJECTID_1 = 0, OBJECTID = 0, Dist = 0, Num = 0, Shape_STAr = NA, Shape_STLe = NA, 
         Council_Me = 'All', Email = NA, created_us = NA, created_da = NA, last_edite = NA, 
         last_edi_1 = NA, ShapeSTAre = NA, ShapeSTLen = NA) %>% 
  dplyr::select(-agg)

# Bind 'all' polygon back to original data 
city_council_dist3 <- rbind(city_council_dist2, all_councils)


demographics_sf <- sf::st_intersection(city_council_dist3, census_transformed) %>% 
  mutate(in_area = units::drop_units(st_area(.))) %>% 
  ### Calc proportional census data based on area of intersection 
  mutate(pop = Population * in_area / c_area, 
         age_u5 = round(age_u5 * in_area / c_area),
         age_5_9 = round(age_5_9 * in_area / c_area),
         age_11_14 = round(age_11_14 * in_area / c_area),
         age_15_17 = round(age_15_17 * in_area / c_area),
         age_18_24 = round(age_18_24 * in_area / c_area),
         age_25_34 = round(age_25_34 * in_area / c_area),
         age_35_44 = round(age_35_44 * in_area / c_area),
         age_45_54 = round(age_45_54 * in_area / c_area),
         age_55_64 = round(age_55_64 * in_area / c_area),
         age_65_74 = round(age_65_74 * in_area / c_area),
         age_75_84 = round(age_75_84 * in_area / c_area), 
         age_o85 = round(age_o85 * in_area / c_area), 
         owner_occupied = round(owner_occupied), 
         renter_occupied = round(renter_occupied)) %>% 
  group_by(OBJECTID, Dist, Council_Me) %>% 
  summarise(pop = sum(pop),
            pop_density = sum(pop)/sum(in_area), 
            age_u5 = sum(age_u5),
            age_5_9 = sum(age_5_9),
            age_11_14 = sum(age_11_14),  
            age_15_17 = sum(age_15_17),  
            age_18_24 = sum(age_18_24),  
            age_25_34 = sum(age_25_34),  
            age_35_44 = sum(age_35_44),  
            age_45_54 = sum(age_45_54),  
            age_55_64 = sum(age_55_64),  
            age_65_74 = sum(age_65_74),  
            age_75_84 = sum(age_75_84),  
            age_o85 = sum(age_o85),
            owner_occupied = sum(owner_occupied),
            renter_occupied = sum(renter_occupied)) %>% 
  ungroup()

```

```{r}
ggplot() +
    geom_sf(data = intrsct, aes(fill = pop_density), alpha = .5, lwd = .25) +
    scale_fill_gradient(trans = "log10", 
                        low = "white",
                        high = "firebrick",
                        labels = scales::comma_format())
```
#Business License Groupings
```{r}
#### Categorize Business Data 
food <- c('RESTAURANTS A-M', 
          'RESTAURANTS N-Z'
          # 'FOOD VENDING MACHINES', #may want to remove
          # 'FOOD VENDING VEHICLES', #may want to remove
          # 'ITINERANT RESTAURANT', #may want to remove
          # 'MOBILE FOOD TRUCK' #may want to remove
          ) 

retail <- c('OPEN AIR VENDORS PRIVATE',
             'OPEN AIR VENDORS PUBLIC',
             'SECOND HAND DEALERS',
             'PRECIOUS METAL DEALERS',
             'PET SHOPS'
             # 'TRANSIENT MERCHANT XMAS TREE', #may want to remove
             # 'TRANSIENT MERCHANT', #may want to remove
             # 'PEDDLER & CANVASSER'
             )

service <- c('ARBORIST/TREE SERVICE',
            'MASSAGE THERAPY',
            'MASSAGE ESTABLISHMENT',
            'TATTOO AND BODY PIERCING ESTABLISHMENTS',
            'AUTOMOTIVE REPAIR & SVC',
            'MECHANICAL LICENSE',
            'TATTOO AND PIERCING ARTIST',
            'VEHICLE REMOVAL',
            'ALARM AGENT',
            'RUBBISH & GARBAGE REMOVAL',
            'SELF SERVICE LAUNDRY',
            'TAXI COMPANY',
            'HOTEL/MOTEL', #could make this a separate category
            'SCRAP METAL /JUNK DEALERS' #included here because generally these are used by people looking to get rid of stuff, not purchase like in retail
            )

entertainment <- c('ADULT BUSINESS',
            'PERFORMING ANIMAL EXHIBITIONS',
            'BUSKER OR SIDEWALK PERFORMER',
            'OUTDOOR MOVIE THEATRE',
            'POOL HALLS')

transportation <- c('TAXI DRIVER',
                    'TAXI VEHICLE',
                    'PUBLIC PARKING FACILITY',
                    'LAWN PARK 10 OR MORE SPACES',
                    'LAWN PARK UNDER 10 SPACES') #group is excluded

charitable <- c('CHARITABLE SOLICITATIONS',
                'DONATION BOXES AND CONTAINERS') #may want to exclude this category entirely

#'unclassified' check for categorization, anything not included in above categories are unclassified. Remove entire categories we might want to be unclassified. 

unclassified <- unique(business_licenses_df$Classifi_1) %>% 
  as_tibble() %>% 
  filter(!value %in% c(food, retail, service, entertainment))

business_licenses_df <- business_licenses_df %>% 
  mutate(business_type = case_when(Classifi_1 %in% food ~ 'Food',
                                 Classifi_1 %in% retail ~ 'Retail',
                                 Classifi_1 %in% service ~ 'Service',
                                 Classifi_1 %in% entertainment ~ 'Entertainment',
                                 TRUE ~ 'Unclassified')
         ) %>% 
  filter(business_type != "Unclassified")

rm("food", "retail", "service", "entertainment","transportation","charitable","unclassified")
```
# Business License Locations 
```{r}

# Give business data same CRS as intersection 
st_crs(business_licenses_df) <- st_crs(intrsct)

# Businesses inside of council districts 
bus_in_district_sf <- st_join(business_licenses_df, city_council_dist2, join = st_intersects) %>% 
  dplyr::select(License_Ye, Business_N, Street_Add, Business_P, business_type, OBJECTID, Classifi_1, Dist, Council_Me) %>% 
  filter(is.na(Council_Me) == FALSE)
```
#Business License Viz
```{r}
pal_business <- colorFactor(palette = 'Set2', domain = bus_in_district_sf$business_type)
bus_in_district_sf$popup <- paste("<b>",bus_in_district_sf$Business_N,"</b><br>",
                                  "Type: ",bus_in_district_sf$Classifi_1,sep ="")

leaflet()  %>%
  addTiles()  %>%
  addCircleMarkers(data = bus_in_district_sf, stroke = 0, fillOpacity = 1, radius = 4) 
```
# Schools

```{r}
# Give school data same CRS as intersection 
st_crs(school_boundaries) <- st_crs(intrsct)

# centroids
school_centroids <- st_centroid(school_boundaries)

# Schools inside of council districts 
school_boundaries_sf <- st_join(school_centroids, city_council_dist2, join = st_intersects) %>% 
  dplyr::select(School, SchoolType, Dist, Council_Me) %>% 
  filter(is.na(Council_Me) == FALSE)
```

# Parks
```{r}
# Give school data same CRS as intersection 
st_crs(parks_df) <- st_crs(intrsct)

# Schools inside of council districts 
parks_sf <- st_join(parks_df, city_council_dist2, join = st_intersects) %>% 
  dplyr::select(Park_Name, Park_Type, Dist, Council_Me) %>% 
  filter(is.na(Council_Me) == FALSE)
```

# Public Works

```{r}
# Give school data same CRS as intersection 
st_crs(public_facilities_df) <- st_crs(intrsct)

# Public facilities inside of council districts 
public_facilities_sf <- st_join(public_facilities_df, city_council_dist2, join = st_intersects) %>% 
  dplyr::select(POPL_NAME, POPL_TYPE, Dist, Council_Me) %>% 
  filter(is.na(Council_Me) == FALSE)
```
=#write data
```{r}
write_rds(demographics_sf,"C:/Users/Nathan/Documents/GitHub/East6/Data Visualizations/Final_Project_East_6_App/data/demographics.rds")

write_rds(bus_in_district_sf,"C:/Users/Nathan/Documents/GitHub/East6/Data Visualizations/Final_Project_East_6_App/data/business_license.rds")

write_rds(school_boundaries_sf,"C:/Users/Nathan/Documents/GitHub/East6/Data Visualizations/Final_Project_East_6_App/data/schools.rds")

write_rds(parks_sf,"C:/Users/Nathan/Documents/GitHub/East6/Data Visualizations/Final_Project_East_6_App/data/parks.rds")

write_rds(public_facilities_sf,"C:/Users/Nathan/Documents/GitHub/East6/Data Visualizations/Final_Project_East_6_App/data/public_facilities.rds")

readRDS("C:/Users/Nathan/Documents/GitHub/East6/Data Visualizations/Final_Project_East_6_App/data/public_facilities.rds")
```


# Below is for reference

```{r}

#intr <- sf::st_intersection(city_council_dist2, census_transformed)
leaflet() %>% 
  addTiles() %>% 
  #addPolygons(data = census) %>% 
  addPolygons(data = city_council_dist, color = 'red') %>% 
  addMarkers(data = public_facilities_df %>% filter(POPL_TYPE == 'POLICE STATION'), popup = ~POPL_NAME) #%>% 
  # addMarkers(data = bus_in_district_sf) ### DONT RUN UNTIL CATEGORIES ARE FILTERED

```







